### ISSUE TITLE
Deploys always cause new function versions even with no changes

### ISSUE THREAD

**Issue by iDVB** [graphboss/aws-sam-webpack-plugin#33]
Isn't `sam deploy` supposed to only upload lambdas if something in the lambda changed?
It seems like any time I change **any** function it creates new function versions for all functions.

![image](https://user-images.githubusercontent.com/189506/75407069-1535fe00-58e0-11ea-8874-badb0cd210f9.png)

Is there a way to only have it update functions with changes? Perhaps my babel or webpack config is wrong? 

Running `yarn build` twice and then using ...
`cmp --silent $old $new || echo "files are different"`
shows files as identical. Maybe something wrong with how I'm running `sam deploy`?

**Comment by buggy** [comment]
It's not only you. I need to investigate what's happening.

**Comment by buggy** [comment]
It seem like `sam package` and `sam deploy` are generating different filenames for the `CodeUri` for the `AWS::Serverless::Function`'s each time it is run. This prevent the duplicate detection from working. I need to look into if further to understand how those names are being generated and what I can do to stop this.

**Comment by buggy** [comment]
It turns out this **_was_** a bug with AWS SAM. If you upgrade to SAM `0.43.0` it should work (you'll need to deploy once).

The long version is this:
Every time webpack ran it re-created the `.aws-sam/build` folder. The structure and file contents were the same but the timestamps were different. The different timestamp meant the zip files uploaded to S3 had different md5's so they were uploaded using different locations. This resulted in the packaged `template.yaml` having different `CodeUri` for each function and CloudFormation then deployed every function every build.

**Comment by iDVB** [comment]
Great! Thanks @buggy. We’ll give this a try today.
